#
# algorithms - Algorithms for Practice
# Copyright © 2020-2021 Subhrodip Mohanta (hello@subho.xyz)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: 2

jobs:
  sonar-pr:
    docker:
      - image: circleci/openjdk:11
    steps:
    - checkout
    - restore_cache:
        key: algo-sonar-pr-{{ checksum "pom.xml" }}
    - run: |
        if [ -n "${CIRCLE_PR_NUMBER}" ]; then
          MAVEN_OPTS="-Xmx3000m" ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
             -Dsonar.pullrequest.key=${CIRCLE_PR_NUMBER} \
             -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} \
             -Dsonar.pullrequest.base=master
        else
          echo "No Sonar PR analysis as this is not a pull request"
        fi
    - save_cache:
        key: algo-sonar-pr-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

workflows:
  version: 2
  all:
    jobs:
    - sonar-pr
