name: Algo CI

on:
  push:
    branches: [ '**', '!master' ]

jobs:
  check-compilation:

    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    
    steps:
      - uses: actions/checkout@master
      
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      
      - name: Cache Maven packages
        uses: actions/cache@master
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build
        run: mvn -B clean verify
  
  
  check-code-formatting:

    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@master
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@master
      with:
        java-version: 1.11
    
    - uses: actions/cache@master
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   
    
    - name: Verify all Java files are formatted correctly according to the Google Java Style Guide
      run: |
        mvn spotless:check
        echo "Run the command './mvnw spotless:apply' to fix Java formatting if this job fails"
