name: Algorithms CI

on:
  push:
    branches: [ '**' ]

jobs:
  check-compilation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   
    - name: Build with Maven
      run: mvn -B clean package
  
  check-code-formatting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify all Java files are formatted correctly according to the Google Java Style Guide
      run: |
        mvn spotless:check
        echo "Run the command './mvnw spotless:apply' to fix Java formatting if this job fails"
